#!/usr/bin/env bash

# Copyright (C) Volodymyr Zhdanov <wight554@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Gather parameters
function parse_parameters()
{
  while [[ "${#}" -ge 1 ]]; do
    case "${1}" in
      "-bt"|"--buildtype")
        shift && enforce_value "${@}"
        BUILDTYPE="${1}" ;;

      "-d"|"--device")
        shift && enforce_value "${@}"
        DEVICE="${1}" ;;

      "-r"|"--rom")
        shift && enforce_value "${@}"
        ROM="${1}" ;;

      "-o"|"--off")
        export POWEROFF=true ;;

      "-c"|"--clean")
        CLEAN=true ;;

      "-s"|"--sync")
        SYNC=true ;;

      *) die "Invalid parameter specified!" ;;
    esac
    shift
  done

  # Default parameters
  [[ -z "${ROM}" ]] && ROM="nitrogen"
  [[ -z "${DEVICE}" ]] && DEVICE="chiron"
  [[ -z "${BUILDTYPE}" ]] && BUILDTYPE="personal"

  # Sanity checks
  [[ "${BUILDTYPE}" != "personal" && "${BUILDTYPE}" != "test" && "${BUILDTYPE}" != "release" ]] && die "Choose build type between personal, release and test!"
  [[ -z "${TOKEN}" && -z "${CHATID}" ]] && die "Telegram bot checks are not satisfied!"
}

# Pretty small one
function sync()
{
  if [[ -n "${SYNC}" ]]
  then
    repo sync
  fi
}

# Go clean if needed, otherwise installclean
function clean()
{
  if [[ -n "${CLEAN}" ]]
  then
    info "Cleaning build directory..."
    mka clobber
  else
    info "Clean not specified, go installclean..."
    mka installclean
  fi
}

function buildrom()
{
  #  Start compilation
  info "Compiling ${ROM} for ${DEVICE}..."
  mka bacon 2>&1 | tee "${HOME}/logs/buildrom.log"

  # Output files
  OUTPUT="$(find "${ROM_PATH}/out/target/product/${DEVICE}" -maxdepth 1 -iname "${ROM}*${DATE}*.zip" )"
  [ "${ROM}" == "lineage" ] && CHANGELOG_PATH="$(find "${ROM_PATH}/out/target/product/${DEVICE}" -maxdepth 1 -iname "Changelog*${DATE}*.txt" )"
  [ "${ROM}" == "nitrogen" ] && CHANGELOG_PATH="${ROM_PATH}/out/target/product/${DEVICE}/nitrogen_${DEVICE}-Changelog.txt"
}

function upload()
{
  checkoutput || endscript "failed"
  FILENAME="$( basename "${OUTPUT}" )"
  if [ "${ROM}" == "nitrogen" ]
  then
    [[ "${BUILDTYPE}" == "personal" ]] && FILENAME=${FILENAME/./-UNSTABLE.}
    [[ "${BUILDTYPE}" == "test" ]] && FILENAME=${FILENAME/./-TEST.}
  fi
  [[ "${BUILDTYPE}" == "personal" ]] && CHATID="${PM}"
  info "Uploading ${FILENAME} to wight554.tk..." && curl -T "${OUTPUT}" -u "${FTPLOGPASS}" ftp://wight554.tk/"${ROM}/${FILENAME}"
  telegram_notify "${FILENAME} can be downloaded [here](http://wight554.tk/${ROM}/${FILENAME}"
  [[ "${BUILDTYPE}" != "personal" ]] && info "Uploading changelog to Telegram..." && telegram_upload "${CHANGELOG_PATH}"
}

#####################
##  RUN THEM ALL!  ##
#####################

# Common script
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"

# If parameters are satisfied, print formatted message about build start
parse_parameters "${@}"
startscript

# Setup enviroment
romenviroment

# Sync if needed
sync

# Cleanup
clean

# Compile ROM
buildrom

# Check if compilation is fine
checkoutput

# Upload if needed
upload

# Print formatted message about script ending
endscript
