#!/bin/bash

# Common script
source "$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" || return; pwd)/common"

# Input
ROM="${1}"
DEVICE="${2}"
GDRIVE="${3}"
ANYKERNEL="${4}"

# Build dirs
ROM_PATH="${HOME}/${ROM}"
AK2_PATH="${HOME}/linux/ak2-${DEVICE}"
BUILD_PATH="${ROM_PATH}/out/target/product/${DEVICE}"

# AK2 zip name
ZIPNAME="PlaceholderKernel-${DEVICE}-$(date +'%Y%m%d')"

# Start tracking time
START="$(date +%s)"

# Check ROM
if [ "${ROM}" == "abc" ]
then
  info "Let's build bootimage karntest ROM..."
elif [ "${ROM}" == "aosip" ]
then
  info "Let's build bootimage for weird birb ROM.."
else
  die "Choose AOSIP or ABC to proceed!"
fi

# Check device
if [ -z "${DEVICE}" ]
then
  die "Choose device to proceed!"
fi

# Setup environment
info "Setting up build environment"
cd "${ROM_PATH}"
. build/envsetup.sh

# Set the device
info "Setting up the device..."
if [ "${ROM}" == "abc" ]
then
  breakfast "${DEVICE}-userdebug"
elif [ "${ROM}" == "aosip" ]
then
  lunch "aosip_${DEVICE}-userdebug"
fi

# Start compilation with log
info "Starting build kernel for ${DEVICE} and saving a build log file"
rm -f "${BUILD_PATH}/{boot.img,kernel}"
mka bootimage 2>&1 | tee "${HOME}/logs/buildromkernel.log"


# If the above was successful
if [[ -f "${BUILD_PATH}/boot.img" ]]
then
  success "Build successful"
  # Go anykernel
  if [ "${ANYKERNEL}" == "ak" ]
  then
    info "Adding kernel to AnyKernel2"
    mv -f "${BUILD_PATH}/kernel" "${AK2_PATH}/Image.gz-dtb"
    cd "${AK2_PATH}"
    zip -r9 "${ZIPNAME}.zip" ./* --exclude="*README*" --exclude="*.zip"  "${ZIPNAME}.zip"
  fi
  # Google Drive upload
  if [ "${GDRIVE}" == "gdrive" ]
  then
    info "Uploading stuffs to Google Drive"
    if [ "${ANYKERNEL}" == "ak" ]
    then
      gdrive upload "${AK2_PATH}/${ZIPNAME}.zip"
    else
      gdrive upload "${BUILD_PATH}/boot.img"
    fi
  fi
# If the build failed
else
  failed "Build failed"
fi

# Stop tracking time
END="$(date +%s)"
info "Build time: $(echo "$(("${END}"-"${START}"))" | awk '{print int($1/60)" minutes and "int($1%60)" seconds"}')"
