#!/bin/bash

# Setup compiler stuff
export USE_CCACHE=1
/usr/bin/ccache -M 50G

# Colors
BLINK_RED="\\033[05;31m"
BLUE="\\033[01;34m"
# BOLD="\\033[1m"
GRN="\\033[01;32m"
RED="\\033[01;31m"
RST="\\033[0m"
# YLW="\\033[01;33m"

# Export username for android props
# KBUILD_BUILD_USER is set in .bashrc
export USER="${KBUILD_BUILD_USER}"


# Shellcheck, are you satisfied now?
export CCACHE JOBS_FLAG

# Make threads
THREADS="$(($(nproc --all) + 1))"
JOBS_FLAG="-j${THREADS}"

# Common ccache variable
CCACHE=$(command -v ccache)

# Alias for echo to print escape codes
function echo() {
    command echo -e "${@}"
}

# Prints an error in bold red and exits the script
die() { echo "${RED}${1}${RST}" 1>&2; exit 1; }

# Prints an info message in bold blue
info() { echo "${BLUE}${1}${RST}" 1>&2; }

# Prints a success message in bold green
success() { echo "${GRN}${1}${RST}" 1>&2; }

# Prints a failed message in bold blinking red
failed() { echo "${BLINK_RED}${1}${RST}" 1>&2; }

# Function for zipping Anykernel2
zip_ak2(){
    mv -f "${COMPILED_IMAGE}" "${AK2_PATH}/Image.gz-dtb"
    cd "${AK2_PATH}" || die "Anykernel2 folder doesn't exist!"
    zip -r9 "${ZIPNAME}" ./* -x "README.md" -x "./*.zip"
}

# Enforces the value needed for two-part flags
function enforce_value() {
    [[ "${#}" -lt 1 ]] && die "A additional value is needed for one of the flags passed to this script!"
}

# Add trap for catching Ctrl-C
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM
