#!/usr/bin/env bash

# Copyright (C) Volodymyr Zhdanov <wight554@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

# Setup compiler stuff
export USE_CCACHE=1
/usr/bin/ccache -M 50G

# Colors
# BLINK_RED="\\033[05;31m"
BLUE="\\033[01;34m"
# BOLD="\\033[1m"
GRN="\\033[01;32m"
RED="\\033[01;31m"
RST="\\033[0m"
YLW="\\033[01;33m"

# Export username for android props
# KBUILD_BUILD_USER is set in .bashrc
export USER="${KBUILD_BUILD_USER}"

# Current date for all scripts
DATE="$(date +'%Y%m%d')"

# Shellcheck, are you satisfied now?
export CCACHE JOBS_FLAG DATE

# Make threads
THREADS="$(($(nproc --all) + 1))"
JOBS_FLAG="-j${THREADS}"

# Common ccache variable
CCACHE=$(command -v ccache)

######################
##  ECHO FUNCTIONS  ##
######################

# Alias for echo to print escape codes
function echo()
{
  command echo -e "${@}"
}

# Prints a formatted info to point out what is being done to the user
function header()
{
  echo "${2}"
  echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
  echo "==  ${1}  =="
  echo "====$(for i in $(seq ${#1}); do echo "=\\c"; done)===="
  echo "${RST}"
}

# Prints an error in red and exits the script
function die() { echo "${RED}${1}${RST}" 1>&2; exit 1; }

# Prints an error message in red
function error() { echo "${RED}${1}${RST}" 1>&2; }

# Prints an info message in blue
function info() { echo "${BLUE}${1}${RST}" 1>&2; }

# Prints a warn message in green
function warn() { echo "${YLW}${1}${RST}" 1>&2; }

#########################
##  VERBOSE FUNCTIONS  ##
#########################

# Start script with formatted message
function startscript()
{
  START="$(date +"%s")" && header "BUILD STARTED!" "${GRN}"
}

# End script with formatted message and build time
function endscript()
{
  if [[ -n "${1}" ]]
  then
    error "${1}"
    header "BUILD FAILED!" "${RED}"
  else
    header "BUILD COMPLETED!" "${GRN}"
  fi
  END="$(date +"%s")"
  info "BUILD TIME: $(format_time "${START}" "${END}")"
  if [[ -n "${POWEROFF}" ]]
  then
    poweroff 2>/dev/null || sudo poweroff
  fi
  die "" # Just in case
}

# Formats the time for the end
function format_time()
{
  MINS="$(((${2} - ${1}) / 60))"
  SECS="$(((${2} - ${1}) % 60))"
  if [[ "${MINS}" -ge 60 ]]
  then
    HOURS="$((MINS / 60))"
    MINS="$((MINS % 60))"
  fi

  if [[ "${HOURS}" -eq 1 ]]
  then
    TIME_STRING+="1 HOUR, "
  elif [[ "${HOURS}" -ge 2 ]]
  then
    TIME_STRING+="${HOURS} HOURS, "
  fi

  if [[ "${MINS}" -eq 1 ]]
  then
    TIME_STRING+="1 MINUTE"
  else
    TIME_STRING+="${MINS} MINUTES"
  fi

  if [[ "${SECS}" -eq 1 && -n "${HOURS}" ]]
  then
    TIME_STRING+=", AND 1 SECOND"
  elif [[ "${SECS}" -eq 1 && -z "${HOURS}" ]]
  then
    TIME_STRING+=" AND 1 SECOND"
  elif [[ "${SECS}" -ne 1 && -n "${HOURS}" ]]
  then
    TIME_STRING+=", AND ${SECS} SECONDS"
  elif [[ "${SECS}" -ne 1 && -z "${HOURS}" ]]
  then
    TIME_STRING+=" AND ${SECS} SECONDS"
  fi

  echo "${TIME_STRING}"
}

# Add trap for catching Ctrl-C
trap 'echo; die "Manually aborted!"' SIGINT SIGTERM

#############################
##  COMPILATION FUNCTIONS  ##
#############################

# Enforces the value needed for two-part flags
function enforce_value()
{
  [[ "${#}" -lt 1 ]] && die "A additional value is needed for one of the flags passed to this script!"
}

function romenviroment()
{
  info "Setting up build environment"

  # Build dirs
  export ROM_PATH="${HOME}/${ROM}"
  export BUILD_PATH="${ROM_PATH}/out/target/product/${DEVICE}"
  export CCACHE_DIR="${HOME}/.ccache-${ROM}"

  # Check ROM
  if [[ "${ROM}" != "lineage" && "${ROM}" != "nitrogen" ]]
  then
    endscript "Only LineageOS and NitrogenOS are supported!"
  fi

  # Setup environment
  cd "${ROM_PATH}" || endscript "ROM dir doesn't exist!"
  source "${ROM_PATH}/build/envsetup.sh"

  # Set the device
  info "Setting up the device..."
  if [ "${ROM}" == "lineage" ]
  then
    breakfast "${DEVICE}"
  elif [ "${ROM}" == "nitrogen" ]
  then
    lunch "nitrogen_${DEVICE}-userdebug"
  fi
}

#  Zipping AnyKernel2
function ramdisk()
{
  [[ -f "${COMPILED_IMAGE}" ]] || endscript "Kernel image doesn't exist!"
  # Common paths
  AK2_PATH="${HOME}/linux/ak2-${DEVICE}"
  KERNEL_NAME="PlaceholderKernel"
  OUTPUT="${AK2_PATH}/${KERNEL_NAME}-${DEVICE}-${DATE}.zip"

  # Move kernel image specified in kernel compilation script
  info "Moving kernel image to AnyKernel2 folder..."
  mv -f "${COMPILED_IMAGE}" "${AK2_PATH}/Image.gz-dtb"

  # Create flashable AnyKernel2 zip
  cd "${AK2_PATH}" || endscript "AnyKernel2 folder doesn't exist!"
  zip -r9 "${OUTPUT}" ./* -x "README.md" -x "./*.zip"
}

# Check if compilation output exists
function checkoutput()
{
  for i in $(seq 0 "$(("${#OUTPUT[@]}"-1))")
  do
    [[ -f "${OUTPUT[${i}]}" && -n "${OUTPUT[${i}]}" ]] || endscript "Nothing to proceed with, output is empty!"
  done && return
  false
}

########################
##  UPLOAD FUNCTIONS  ##
########################

# Notify Telegram chat about smth
function telegram_notify()
{
  curl -s https://api.telegram.org/bot"${TOKEN}"/sendMessage -d parse_mode="Markdown" -d text="${1}" -d chat_id="${CHATID}" >> /dev/null
}

# Upload file to Telegram chat
function telegram_upload()
{
  curl -s https://api.telegram.org/bot"${TOKEN}"/sendDocument -F document=@"${1}" -F chat_id="${CHATID}" >> /dev/null
}

# Uploads all the things to specified place
function personal_upload() {
  # Proper chatid
  CHATID="${PM}"
  # Check if everything is fine
  for FILE in "${OUTPUT[@]}"
  do
    info "Uploading $( basename "${FILE}" ) to Telegram..." && telegram_upload "${FILE}"
  done
}
