#!/bin/bash

# Setup compiler stuff
export USE_CCACHE=1
/usr/bin/ccache -M 50G

# Colors
BLINK_RED="\033[05;31m"
BLUE="\033[01;34m"
BOLD="\033[1m"
GRN="\033[01;32m"
RED="\033[01;31m"
RST="\033[0m"
YLW="\033[01;33m"

# Export username for android props
# KBUILD_BUILD_USER is set in .bashrc
export USER=$KBUILD_BUILD_USER

# MAKE THREADS
THREADS=$(($(nproc --all) + 1))
JOBS_FLAG="-j${THREADS}"

# Alias for echo to print escape codes
function echo() {
    command echo -e "${@}"
}

# Prints an error in bold red and exits the script
die() { echo "${RED}${1}${RST}" 1>&2; exit 1; }

# Prints an info message in bold blue and exits the script
info() { echo "${BLUE}${1}${RST}" 1>&2; }

# Prints a success message in bold green and exits the script
success() { echo "${GRN}${1}${RST}" 1>&2; }

# Prints a failed message in bold green and exits the script
failed() { echo "${RED}${1}${RST}" 1>&2; }
